#########################
# anki.yml
#########################
#
# This container runs anki

services:
  # ####################
  # An example of running an unprivileged X11 app in this environment.
  anki:
    image: ghcr.io/yitzhakbg/anki:edge
    #   build:
    #     context: ./images/anki
    #     args:
    #       BASE_IMAGE: ${BUILD_BASE_IMAGE}
    #       BASE_APP_IMAGE: ${BUILD_BASE_APP_IMAGE}
    runtime: ${DOCKER_RUNTIME}
    volumes:
      - ${XORG_SOCKET}:/tmp/.X11-unix
      - ${PULSE_SOCKET_HOST}:${PULSE_SOCKET_GUEST}
      # Home directory: downloads, etc
      - ${LOCAL_STATE}/:/home/retro/

    env_file:
      - config/common.env
      - config/xorg.env
      # This line tells run-gow to insert GPU-specific config here
      # run-gow: gpu_env

    environment:
      LOG_LEVEL: info
